Create Learning_Management_Sysytem.md
fosslk/OSS-Training-Project pull request #9
Opened 2020-12-15 11:53 UTC by kalindut

2020-12-19 02:40 UTC, dhanushkac requested changes
File name supposed to be changed to Learning_Management_Systems.md

2020-12-19 02:40 UTC, dhanushkac commented on Investigations/Learning_Management_Sysytem.md
> +</p>
This part is not needed since this is text only doc.

2020-12-19 02:40 UTC, dhanushkac commented on Investigations/Learning_Management_Sysytem.md
> +<hr>
use -- for hr in md

2020-12-19 02:40 UTC, dhanushkac commented on Investigations/Learning_Management_Sysytem.md
> +<hr>
Last line won't need hr

2020-12-24 07:50 UTC, kalindut commented
Done the changes. ayye



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/24/20,
01:20:35 PM

On Sat, Dec 19, 2020 at 8:10 AM Dhanushka Chandana <notifications@github.com>
wrote:

> *@dhanushkac* requested changes on this pull request.
>
> File name supposed to be changed to Learning_Management_Systems.md
> ------------------------------
>
> In Investigations/Learning_Management_Sysytem.md
> <https://github.com/fosslk/OSS-Training-Project/pull/9#discussion_r546179014>
> :
>
> > +<p align="center">
>
> +    <img
>
> +       alt="E_learn"
>
> +      src="http://eduadvice.in/images/uploads/title/27442020044438ONLINE_LEARNING.jpg"
>
> +      width="800"
>
> +    />
>
> +  </a>
>
> +</p>
>
>
> This part is not needed since this is text only doc.
> ------------------------------
>
> In Investigations/Learning_Management_Sysytem.md
> <https://github.com/fosslk/OSS-Training-Project/pull/9#discussion_r546179098>
> :
>
> > +* Online portal
>
> +* Quiz wizard
>
> +* Rich media support
>
> +* Messaging
>
> +
>
> + **Pricing :**
>
> +
>
> +Free to use. Moodle’s open-source code allows anyone to install it in their own servers for free.
>
> +Pricing based on the number of users and file storage.
>
> +
>
> +Subscription plans include:
>
> +*Free: $0 (50 users, 200MB*.
>
> +*Starter: $80/year (50 users, 200MB) with some add-on features*.
>
> +*Moodle for School: Mini – $250/year (100 users, 200MB), Small: $500/year (200 users, 400MB), Medium: $1,000/month (500 users, 1GB)*.
>
> +
>
> +<hr>
>
>
> use -- for hr in md
> ------------------------------
>
> In Investigations/Learning_Management_Sysytem.md
> <https://github.com/fosslk/OSS-Training-Project/pull/9#discussion_r546179150>
> :
>
> > +* Users management
>
> +* User collaboration tools
>
> +* Forums
>
> +* Email messaging and notification
>
> +* Chat
>
> +* Lessons and Tutorials manager
>
> +* Podcast support
>
> +* Syllabus manager
>
> +* Attendance manager
>
> +* Tracking and statistics
>
> +* Performance reporting
>
> +* Evaluation system
>
> +* Tests and quiz management
>
> +* REST-API support
>
> +
>
> +<hr>
>
>
> Last line won't need hr
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fosslk/OSS-Training-Project/pull/9#pullrequestreview-555909147>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APVVSSADM4RDXUC4CV6VYODSVQHBXANCNFSM4U4HDRBQ>
> .
>

2020-12-26 05:31 UTC, dhanushkac reviewed
Update file name to `Learning_Management_Systems.md`

2020-12-26 05:32 UTC, dhanushkac requested changes
Follow the markdown guide here https://www.markdownguide.org/

2021-01-06 16:36 UTC, kalindut commented
I was done the changes..

2021-08-08 15:38 UTC, kasvith commented on Investigations/Learning_Management_Sysytem.md
> +   # Learning Management Systems
```suggestion
# Learning Management Systems
```

2021-08-13 10:42 UTC, closed without merging